[2018/01/08 15:39:10] :: [pool-1-thread-10] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2018/01/08 15:39:10] :: [pool-1-thread-10] :: Current Thread Name for the test is "pool-1-thread-10"<br><br>[2018/01/08 15:39:22] :: [pool-1-thread-10] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2018/01/08 15:39:36] :: [pool-1-thread-10] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2018/01/08 15:39:37] :: [pool-1-thread-10] :: The user has creating SalesCredit_NonInvorder<br><br>[2018/01/08 15:39:38] :: [pool-1-thread-10] :: Successfully navigated to Home page<br><br>[2018/01/08 15:39:39] :: [pool-1-thread-10] :: File path is = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\ .<br><br>[2018/01/08 15:39:59] :: [pool-1-thread-10] :: Exception occurred. null<br><br>[2018/01/08 15:40:10] :: [pool-1-thread-10] :: Closing the Browser Instance<br><br>[2018/01/08 15:40:10] :: [pool-1-thread-10] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: sfdc.java Method name: loginUserNameAccountID(395)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/NON/Credit_Advantage_DL2.feature Method name: When I am entering "Emily Morrison" and launch "1"(9)<br><br>Complete Error Message: null<br><br><br>