[2018/01/04 13:08:14] :: [pool-1-thread-17] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2018/01/04 13:08:14] :: [pool-1-thread-17] :: Current Thread Name for the test is "pool-1-thread-17"<br><br>[2018/01/04 13:08:41] :: [pool-1-thread-17] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2018/01/04 13:08:42] :: [pool-1-thread-17] :: The user has creating RetentionBuyOut_Invorder<br><br>[2018/01/04 13:08:58] :: [pool-1-thread-17] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2018/01/04 13:09:29] :: [pool-1-thread-17] :: Unable to navigate to Home page<br><br>[2018/01/04 13:09:33] :: [pool-1-thread-17] :: Closing the Browser Instance<br><br>[2018/01/04 13:09:33] :: [pool-1-thread-17] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: SalesForce.java Method name: verifyHP(198)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/AMD_CANCEL/Order_BuyOut_CFCB_DL.feature Method name: Then I should be in "Home" page(8)<br><br>Complete Error Message: null<br><br><br>