[2017/05/31 17:57:23] :: [pool-1-thread-4] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/05/31 17:57:23] :: [pool-1-thread-4] :: Current Thread Name for the test is "pool-1-thread-4"<br><br>[2017/05/31 17:58:17] :: [pool-1-thread-4] :: The user has launched 'http://test.salesforce.com<br><br>[2017/05/31 17:58:40] :: [pool-1-thread-4] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2017/05/31 17:59:16] :: [pool-1-thread-4] :: Exception occurred. null<br><br>[2017/05/31 17:59:25] :: [pool-1-thread-4] :: Closing the Browser Instance<br><br>[2017/05/31 17:59:25] :: [pool-1-thread-4] ::  File Name: Assert.java Method name: fail(91)<br> File Name: Assert.java Method name: assertTrue(43)<br> File Name: Assert.java Method name: assertTrue(54)<br> File Name: Common.java Method name: changeStatusSales(165)<br> File Name: SalesForce.java Method name: loginSF(100)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/CURRENT_MONTH_AMEND_COMMISSIONS/Copy of Inventory_Current_Month_Amend_Commission.feature Method name: When I login to SalesForce(6)<br><br>Complete Error Message: <br><br><br>