[2017/12/20 12:11:11] :: [pool-1-thread-1] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/12/20 12:11:11] :: [pool-1-thread-1] :: Current Thread Name for the test is "pool-1-thread-1"<br><br>[2017/12/20 12:11:12] :: [pool-1-thread-1] :: File path is = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\ .<br><br>[2017/12/20 12:11:31] :: [pool-1-thread-1] :: The user has launched '1<br><br>[2017/12/20 12:11:31] :: [pool-1-thread-1] :: Successfully navigated to LandingHome page<br><br>[2017/12/20 12:11:41] :: [pool-1-thread-1] :: Successfully clicked on ContinueBtn .<br><br>[2017/12/20 12:11:53] :: [pool-1-thread-1] :: [Ljava.lang.String;@5e57ad2a<br><br>[2017/12/20 12:12:01] :: [pool-1-thread-1] :: [Ljava.lang.String;@5e57ad2a<br><br>[2017/12/20 12:12:08] :: [pool-1-thread-1] :: [Ljava.lang.String;@5e57ad2a<br><br>[2017/12/20 12:12:16] :: [pool-1-thread-1] :: Exception occurred. C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\LandingPageData.xlsx (The process cannot access the file because it is being used by another process)<br><br>[2017/12/20 12:12:17] :: [pool-1-thread-1] :: Closing the Browser Instance<br><br>[2017/12/20 12:12:17] :: [pool-1-thread-1] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: LandingPage.java Method name: gettingOfferDetails(261)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/DAILY_REGRESSION/AR_LANDING_PAGE/ARLandingPage_DoNotRenewAcceptOfferDR.feature Method name: And I am check "Accept" and submiting(8)<br><br>Complete Error Message: null<br><br><br>