[2017/03/17 12:38:17] :: [pool-1-thread-1] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/03/17 12:38:17] :: [pool-1-thread-1] :: Current Thread Name for the test is "pool-1-thread-1"<br><br>[2017/03/17 12:38:45] :: [pool-1-thread-1] :: The user has launched 'http://test.salesforce.com<br><br>[2017/03/17 12:38:45] :: [pool-1-thread-1] :: The user has creating Neworder<br><br>[2017/03/17 12:39:11] :: [pool-1-thread-1] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2017/03/17 12:39:11] :: [pool-1-thread-1] :: File path is = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\ .<br><br>[2017/03/17 12:39:22] :: [pool-1-thread-1] :: Successfully New order account ID Fetched= readSFInputData .<br><br>[2017/03/17 12:39:31] :: [pool-1-thread-1] :: Successfully Account ID is visible= 001j000000bYqig .<br><br>[2017/03/17 12:40:02] :: [pool-1-thread-1] :: Successfully Account Name is visible 001j000000bYqig .<br><br>[2017/03/17 12:40:02] :: [pool-1-thread-1] :: Successfully switched in to frame<br><br>[2017/03/17 12:40:03] :: [pool-1-thread-1] :: Rich Moringis having Primary contact<br><br>[2017/03/17 12:40:15] :: [pool-1-thread-1] :: Exception occurred. org.openqa.selenium.interactions.Actions cannot be cast to org.openqa.selenium.interactions.Action<br><br>[2017/03/17 12:40:17] :: [pool-1-thread-1] :: Closing the Browser Instance<br><br>[2017/03/17 12:40:18] :: [pool-1-thread-1] ::  File Name: Assert.java Method name: fail(91)<br> File Name: Assert.java Method name: assertTrue(43)<br> File Name: Assert.java Method name: assertTrue(54)<br> File Name: SalesForce.java Method name: creatingPrimaryContactrelationship(821)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/UNIT_TESTING/ChangeAcconntRelationship/Change_Account_Relation_Ship_XL.feature Method name: Then I am creating primary contact relationship(9)<br><br>Complete Error Message: <br><br><br>