[2017/12/18 12:12:08] :: [pool-1-thread-6] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/12/18 12:12:08] :: [pool-1-thread-6] :: Current Thread Name for the test is "pool-1-thread-6"<br><br>[2017/12/18 12:12:18] :: [pool-1-thread-6] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2017/12/18 12:12:19] :: [pool-1-thread-6] :: The user has creating SalesCreditINVorder<br><br>[2017/12/18 12:12:35] :: [pool-1-thread-6] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2017/12/18 12:12:37] :: [pool-1-thread-6] :: Successfully navigated to Home page<br><br>[2017/12/18 12:12:39] :: [pool-1-thread-6] :: File path is = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\ .<br><br>[2017/12/18 12:13:32] :: [pool-1-thread-6] :: Successfully Account ID is visible= Empty .<br><br>[2017/12/18 12:14:10] :: [pool-1-thread-6] :: Successfully clicked on GlobalSearchBtn .<br><br>[2017/12/18 12:14:48] :: [pool-1-thread-6] :: Successfully clicked on PeopleName .<br><br>[2017/12/18 12:15:08] :: [pool-1-thread-6] :: Successfully clicked on FollowDown .<br><br>[2017/12/18 12:15:23] :: [pool-1-thread-6] :: Successfully clicked on UserDetail .<br><br>[2017/12/18 12:15:45] :: [pool-1-thread-6] :: Successfully clicked on LoginUsers .<br><br>[2017/12/18 12:16:27] :: [pool-1-thread-6] :: Tab is not available,AccountDetails<br><br>[2017/12/18 12:17:15] :: [pool-1-thread-6] :: Exception occurred. null value in entry: id=null<br><br>[2017/12/18 12:17:22] :: [pool-1-thread-6] :: Closing the Browser Instance<br><br>[2017/12/18 12:17:22] :: [pool-1-thread-6] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: NonInventory1.java Method name: createNewSalesCancelQuote(508)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/AMD1/New_Sales_Credit_Inventory_CFCB_EUT.feature Method name: Then Creating Quote for new sales cancel Inventory with "Connection(SM) for Co-Brokerage-97405","Credit" and "10" and "<NoCancelType>" and "NoCancellationReason"(11)<br><br>Complete Error Message: null<br><br><br>