[2017/10/13 16:43:06] :: [pool-1-thread-19] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/10/13 16:43:07] :: [pool-1-thread-19] :: Current Thread Name for the test is "pool-1-thread-19"<br><br>[2017/10/13 16:43:32] :: [pool-1-thread-19] :: Error occured in the function GetWebDriver and error message is Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: 'BRIDT-1383', ip: '192.168.233.192', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_141'
Driver info: driver.version: Driver, Stopping execution<br><br>[2017/10/13 16:43:33] :: [pool-1-thread-19] :: Exception occurred. null<br><br>[2017/10/13 16:43:33] :: [pool-1-thread-19] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: SalesForce.java Method name: launchSF(51)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/A2B_OrderValidation/Copy of Copy (3) of OrderFieldValidationForAllTC.feature Method name: Given I launch salesforce test portal(5)<br><br>Complete Error Message: null<br><br><br>