[2018/02/15 17:35:30] :: [pool-1-thread-14] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2018/02/15 17:35:30] :: [pool-1-thread-14] :: Current Thread Name for the test is "pool-1-thread-14"<br><br>[2018/02/15 17:35:49] :: [pool-1-thread-14] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2018/02/15 17:35:50] :: [pool-1-thread-14] :: The user has creating SalesCredit_Invorder<br><br>[2018/02/15 17:36:08] :: [pool-1-thread-14] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2018/02/15 17:36:39] :: [pool-1-thread-14] :: Unable to navigate to Home page<br><br>[2018/02/15 17:36:43] :: [pool-1-thread-14] :: Closing the Browser Instance<br><br>[2018/02/15 17:36:43] :: [pool-1-thread-14] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: SalesForce.java Method name: verifyHP(198)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/Cancel/New_Sales_Credit_Inventory_CFCB_DR4.feature Method name: Then I should be in "Home" page(8)<br><br>Complete Error Message: null<br><br><br>